project_id = "rqnknqgpqttjqqhaejmt"

[functions.send-admin-notification]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
